### ISSUE TITLE
Room for only my tweets and @mentions

### ISSUE THREAD

**Issue by plinss** [Half-Shot/matrix-appservice-twitter#10]
It would be useful to have a room that only shows tweets from the linked account as well as when the linked account is @mentioned by others, instead of the entire feed.

This allows matrix users (may be members of a team that share a twitter account) to get notifications for only those events rather than for every tweet that shows in the timeline.

The slack<->twitter bridge works this way.

**Comment by Half-Shot** [comment]
Seems like a good idea. I'm thinking about giving users the option to toggle things like this in a future release.

**Comment by Half-Shot** [comment]
ee73701 adds support for setting your own filters. You can do this via the service room through the commands listed in help. 

I'll close the issue for now. Let me know if this wasn't what you had in mind.
