### ISSUE TITLE
Ability to become room admin

### ISSUE THREAD

**Issue by plinss** [Half-Shot/matrix-appservice-twitter#11]
Since the timeline room is created by the service, a regular user can't modify the room to list it in the server's directory, change its address, or title, etc.

At some point server admins may get these capabilities, but in the meanwhile, it would be nice to have a command in the control room that has the service promote another user to an admin.

**Comment by Half-Shot** [comment]
Users now have control over their timelines ( 528ae93f32c1853e67a01532a8b0d0c903d4fb43 ), and we also support bridging existing rooms with either a hashtag or timeline ( c242e40cd4926e668358a6e1dd90cc0bf0b3a01e )

It's impossible however to do this via the alias system as the bridge isn't aware of the requester.
