### ISSUE TITLE
Have link to the profile in end or beginning of timeline room topic

### ISSUE THREAD

**Issue by Mikaela** [Half-Shot/matrix-appservice-twitter#17]
It would be especially useful if you want to retweet something as having a link would turn typing the address manually or searching at Twitter into just clicking the link (or with older tweet scrolling down) and retweet button

**Comment by Half-Shot** [comment]
1a4f34fb9562b9a65123b365a893d91dabcc52ea should fix this for you.

Be aware that users will need to change their description for it to update due to how it works, but all _future_ rooms will have this.
