### ISSUE TITLE
Tweet Truncation

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-twitter#31]
https://matrix.to/#/!NbTssxRUWRYtpBMWeF:half-shot.uk/$14799835409271gWULY:half-shot.uk

>Looks like Twitter truncate tweets after applying shortened urls...great.
>Ahh
>Twitter doesn't count media as text, but they will put media urls in the text, and then truncate it.
>Great
>https://dev.twitter.com/overview/api/upcoming-changes-to-tweets Looks like a recent parameter got put in for just this, but is only enabled by default on stream APIs (so user timelines). Well, mystery solved.

Need to pass in ``extended_tweet`` on my requests. Streams do this by default but the old REST APIs do not.

**Comment by Half-Shot** [comment]
Fixed by 076efe16a74a82892f182cd1450fc73fb0ed908a

**Comment by lukebarnard1** [comment]
Somehow, it looks like RTs are still truncated.

**Comment by Half-Shot** [comment]
You're kidding... alright. Let's have a look

**Comment by Half-Shot** [comment]
6085a51 should have fixed this now.
