### ISSUE TITLE
Profile avatars are sometimes set after a tweet is bridged to a message 

### ISSUE THREAD

**Issue by lukebarnard1** [Half-Shot/matrix-appservice-twitter#53]
![2016-12-20-145456_349x145_scrot](https://cloud.githubusercontent.com/assets/6750344/21355048/732a7902-c6c4-11e6-9f9d-edd618a93e3a.png)

**Comment by Half-Shot** [comment]
This is actually more of an upstream problem. I do what I can in #44 to make it wait for profiles to be sent, but the bridge lib doesn't seem to wait for a confirmation of the profile being set and so I can't use promises to hold off on tweet processing.

**Comment by lukebarnard1** [comment]
ah... that's a bit rubbish.. I'll ask Leo, he might know something about this

**Comment by Half-Shot** [comment]
Looking closer, this looks like a repeat of #32. The display names might be getting there before the avatars, but it very much falls down to the same problem.
