### ISSUE TITLE
Weird link muddling

### ISSUE THREAD

**Issue by lukebarnard1** [Half-Shot/matrix-appservice-twitter#56]
Message text on Matrix:
"Update on Zuck & Media: He's consistent on seeing Fb as a place for "public discourse" httphttps://techcrunch.com/2016/12/21/fbonc/t I think that means: https://t.co/SherXcuA2d"

And on Twitter:
"Update on Zuck & Media: He's consistent on seeing Fb as a place for "public discourse" https://techcrunch.com/2016/12/21/fbonc/ … What I think that means:"

**Comment by Half-Shot** [comment]
I suspect it's because I'm transforming it in the wrong place or something. Let's investigate..

**Comment by Half-Shot** [comment]
https://github.com/Half-Shot/matrix-appservice-twitter/commit/e6fad231780ca293f9fe901034aaf3ad0ed4d74e should fix this. I moved the expansion code out and wrote some tests for it :)

**Comment by Half-Shot** [comment]
Closing as it seems to be fixed. If anyone has this problem, feel free to open it and boo me.
