### ISSUE TITLE
Ability to set a format for the Matrix user's display name

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-twitter#57]
Scenario: We use the bridge to push our organization's social media posts into the general chat room. It looks a little creepy to see the ghost users in the room 'talking'.

It would be nice to be able to set a format to reduce some of the ghosting from the display name. For instance, having all accounts show up as `Twitter - ThePerson` instead of `ThePerson` would be desirable. 

Would only need basic format specifiers: `@username` and display name.

*If I ever have free time on my hands, I'd be glad to submit a PR for this*

**Comment by Half-Shot** [comment]
Sounds very sensible and quite easy to do, I'll make a note of it :+1:

**Comment by Half-Shot** [comment]
Belated Christmas present for you :sweat_smile:  https://github.com/Half-Shot/matrix-appservice-twitter/pull/70

**Comment by turt2live** [comment]
Thanks :D 

It looks promising. I don't currently have a way to test it, yet. We're planning on deploying our own to give matrix.org a small break.

**Comment by Half-Shot** [comment]
(Merged #70)
