### ISSUE TITLE
HS rate limiting causes hammering of the HS

### ISSUE THREAD

**Issue by lukebarnard1** [Half-Shot/matrix-appservice-twitter#58]
The matrix.org bridge is currently down because the sending of events is never given up on. One event was observed being sent to the HS > 2500 times in a single log file. The requests to send the event were failing due to HS rate limiting, which admittedly can be turned off for app services. However, the bridge needs to actually wait the suggested delay sent from the HS instead of  blindly retrying constantly.

**Comment by lukebarnard1** [comment]
The default of "send everything in the queue every 150MS" might need to be adjusted, or configurable.

**It turns out the default `Scheduler` from matrix-js-sdk is being used, which will just retry forever. There is one scheduler per AS user (one of those per Twitter account) and so there are multiple queues of messages being served separately.**

One solution would be a queue on the bridge that does better rate limiting than retrying thousands of times on several messages at once.

This needs further investigation, and it would probably be a good idea to do some per-room (or twitter account?) queuing on the bridge so that when the most popular twitter account on matrix sends a tweet into 5000 rooms, the HS doesn't die... Come to think of it, could timeline linking even scale well in this situation?

**Comment by lukebarnard1** [comment]
Relevant discussion [here](https://matrix.to/#/!NbTssxRUWRYtpBMWeF:half-shot.uk/$1483981739704SVJPv:half-shot.uk)

**Comment by lukebarnard1** [comment]
Looking at the logs further, I cannot determine that the bridge request bunching is causing the issues that were being seen. Somehow the js-sdk scheduling was failing, but the HS was sending the same "retry_after_ms" repeatedly:

WARN matrix-appservice-bridge [-] PUT http://matrix.org/_matrix/client/r0/rooms/!YKYINcEqjdxGQgeOLW%3Amatrix.org/send/m.room.message/m1483342672416.452 (@_twitter_767144354:matrix.org) HTTP 429 Error: {"errcode":"M_LIMIT_EXCEEDED","error":"Too Many Requests","retry_after_ms":2406}

was logged 940 times, for example. Determining whether these all happened in quick succession is Hard because there are no timestamps in the logs.

**Comment by Half-Shot** [comment]
ab5661eaaf88cedb20df758580d9a77d17139084 is expected to limit the hammering during startup, and hopefully fix the problem here to an extent.

**Comment by Half-Shot** [comment]
I'm going to close this on the basis my HS seems to be coping quite well without any mucking about with the DB, so I expect this will just work for a lot of people. Thanks :+1:
