### ISSUE TITLE
No logs to the console

### ISSUE THREAD

**Issue by lukebarnard1** [Half-Shot/matrix-appservice-twitter#63]
Logging is only going to the log file(s).

**Comment by Half-Shot** [comment]
Remove [this](https://github.com/Half-Shot/matrix-appservice-twitter/blob/develop/config/config.sample.yaml#L28) line ?

**Comment by lukebarnard1** [comment]
I thought the current behaviour is that logging goes to both the log file, configured ^there, _and_ the console. Apparently, the logrotate winston transport causes the console logging to vanish. 

Removing the logrotate transport does indeed allow console logging to function correctly.

AH. https://github.com/juttle/winston-logrotate/issues/4

**Comment by lukebarnard1** [comment]
So it looks like `winston-logrotate` is doing [evil things](https://github.com/juttle/winston-logrotate/blob/master/lib/winston-logrotate.js#L127) by clobbering the getters for stdout, stderr entirely.

**Comment by Half-Shot** [comment]
Aww :cry:

**Comment by lukebarnard1** [comment]
Having changed that, things work, but it seems that this library also doesn't pass `formatter` so we can't have our logs looking the same. At this point it would probably be best to use the daily rotation logs provided by winston or roll a `winston-logrotate` thing ourselves: their's is only 150lines and not that complicated.

**Comment by Half-Shot** [comment]
Fixed by #93
